server:
  port: 7001

spring:
  application:
    name: cloud-eureka-cluster-server
  security:
    user:
      name: root
      password: root
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  #    hostname: erureka1
  client:
    fetch-registry: true  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false #不需要向eureka注册中心中注册自己
    service-url:
      defaultZone: http://root:root@eureka2:7002/eureka/,http://root:root@eureka3:7003/eureka/