server:
  port: 7001

spring:
  application:
    name: eureka-server-7001
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false #不需要王eureka注册中心中注册自己
    fetch-registry: false   #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
#  server:
#    enable-self-preservation: false #关闭自我保护机制，保证不可用服务被及时踢除
#    eviction-interval-timer-in-ms: 2000
