spring:
  application:
    name: boot-admin-eureka-consumer
  boot:
    admin:
      client:
        url: http://127.0.0.1:3001
        instance:
          prefer-ip: true
server:
  port: 3003
#开放端点用于SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        #开放所有页面节点  默认只开启了health、info两个节点
        include: '*'
  endpoint:
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

